### ISSUE TITLE
Updating Treatment Cost Table is not Impacting Sampled Parameters (shiny-ivi-ra-experts model)

### ISSUE THREAD

**Issue by jflevy** [InnovationValueInitiative/IVI-RA#3]
Under 'Parameter Values'>'Formal Health Care Sector' 

If you modify  parameters in the "Treatment Cost" table such as 'price per unit' or 'discount (lower)' when you simulate, it continues to use the default values for these parameters. This is not true of other parameters on the parameter values screen (though is true of all inputs in the Treatment Cost table). 

Note: I modified all price per units to be 5,000 and set different discount defaults:
![image](https://user-images.githubusercontent.com/10618511/33669989-e18f5d10-da71-11e7-9be1-0e6b71c81a28.png)

Yet after running the model these values were not changed: 
![image](https://user-images.githubusercontent.com/10618511/33670110-43f59686-da72-11e7-9809-453269f284b3.png)

**Comment by dincerti** [comment]
A new version of the web application has been deployed and this issue has been fixed. Thanks for pointing out the bug!
