### ISSUE TITLE
Application to other diseases

### ISSUE THREAD

**Issue by rrosal** [InnovationValueInitiative/IVI-RA#4]
Hi,

 I wanted to reach out to ask more about the IVI-RA model. I was looking through the source code of the model and was curious to see if the source code could be modified for a different therapeutic area. How extensive would the workload be if we try to modify the model to a different disease?

Thanks!

**Comment by dincerti** [comment]
Hi,

Unfortunately disease models in RA are very specific to RA. This is one of the reasons that we (and many others) have built an individual patient simulation and is unlike some other therapeutic areas where state transition models are common.

That said, we have used some general techniques. For example, R is a pretty good tool for randomly sampling from probability distributions for probabilistic sensitivity analysis. You might also take a look at the C++ source code to see how you can use random sampling for an individual patient level simulation (note that R and other non-compiled programming languages are really too slow to do this). 

Finally, I would point out that our package hesim is meant to be a general purpose R package for building and analyzing health-economics simulation models. It contains much of the architecture used to build the IVI-RA model and is being actively developed. More features will continue to be added.
