### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by davidtrueman** [InnovationValueInitiative/IVI-RA#5]
Hi there. I'm struggling to install the package and receive errors on installation of hesim. I wondered if you had come across this before and knew what might be causing it? I attach my console output. I'm using 64-bit R 3.5.1 on Windows 10. Thanks in advance!
[log.txt](https://github.com/InnovationValueInitiative/IVI-RA/files/2333168/log.txt)

**Comment by dincerti** [comment]
I've made a new commit with hesim that should fix the issue. Let me know if you are still having problems!

**Comment by davidtrueman** [comment]
Thank you for your prompt response and help! I do get further in the installation now, but I still have errors on hesim. I attach the new output! Thanks again
[log2.txt](https://github.com/InnovationValueInitiative/IVI-RA/files/2335413/log2.txt)

**Comment by davidtrueman** [comment]
Actually please ignore my last message - after a system restart it seems to have installed now. Thanks!

**Comment by dincerti** [comment]
Glad to hear, thanks for reporting the error!
