### ISSUE TITLE
missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by dshakey** [InnovationValueInitiative/IVI-RA#7]
> # install.packages("devtools")
> library(devtools)
> devtools::install_github("InnovationValueInitiative/IVI-RA")
Downloading GitHub repo InnovationValueInitiative/IVI-RA@master
Error in if (!file.info(path)$isdir) { :
  missing value where TRUE/FALSE needed

**Comment by dincerti** [comment]
Hi, were you able to resolve this? I am still able to install correctly from GitHub on OSX, but have not yet tried on PC.

**Comment by dshakey** [comment]
Yes. I upgraded to r 3.5.3 from 3.3.3
